# Generated by Django 4.2.7 on 2026-01-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentscheme',
            name='category',
            field=models.CharField(choices=[('health', 'आरोग्य'), ('education', 'शिक्षण'), ('agriculture', 'शेती विषयक'), ('infrastructure', 'सार्वजनिक सुखसुविधा'), ('social', 'आवास योजना'), ('skill', 'कौशल्य विकास'), ('other', 'इतर')], max_length=50),
        ),
        migrations.AlterField(
            model_name='panchayatmember',
            name='position',
            field=models.CharField(choices=[('sarpanch', 'सरपंच (Village Head)'), ('upsarpanch', 'उप सरपंच (Deputy Head)'), ('member', 'सदस्य'), ('secretary', 'सचिव'), ('treasurer', 'कर्मचारी'), ('other', 'संगणक परिचालक')], max_length=50),
        ),
    ]
